### ISSUE TITLE
Duplicate user names

### ISSUE THREAD

**Issue by kneasle** [lelandpaul/ringingroom#161]
It appears that you can create multiple accounts with the same user name.  However, to tell who a bell is assigned to the code currently performs an equality test of the user name strings, not user IDs.  Thus, if two people with identical usernames were to join a tower, Ringing Room would treat them as one person.

I also want to avoid people creating an account called Wheatley because otherwise there would be no way to prevent Wheatley from ringing their bells, and in doing so I could potentially kill two birds with one stone by asserting that the usernames are unique.

**Comment by lelandpaul** [comment]
We're aware of the potential for this problem; this is some technical debt left over from when we first deployed user accounts.

I'd prefer not to force usernames to be unique — for one, the migration problems are a headache. (If there are duplicate names now, how do you decide who gets to keep their name and who needs to change?)

Instead, I'm intending to make it so that clients are handling assignments by user IDs. This will also make certain other features that depend on clients communicating with the server about specific users (e.g. "on-the-fly" host assignment) easier to implement. Thanks for pointing out that this interacts with Wheatley — I'll make it a priority.
