### ISSUE TITLE
Add alternate keys for 'bob' and 'single'

### ISSUE THREAD

**Issue by kneasle** [lelandpaul/ringingroom#164]
Currently, the keys for calling `Bob` and `Single` (`B`/`N`), whilst intuitive to remember are really inconvenient to press whilst ringing handbells since they require the same fingers as `F`/`J`.  To remedy this, I suggest that we add `O`/`I` for `bOb` and `sIngle` as alternate keybindings, since they can be pressed without moving fingers off either `F` or `J`.

**Comment by BrynMarieR** [comment]
We're actually planning to make these keybindings customizable (along with customizable bindings for ringing the two bells)

**Comment by kneasle** [comment]
Oh nice! That's cool to see.  But I still think that we should do something to make sure that people don't have to reconfigure their keybindings in order to actually call touches - I'm not sure what we could do without having to implement multiple keybindings for everything or straight-up changing the default keys.

**Comment by BrynMarieR** [comment]
We've decided that the best solution now -- especially as so many are giving calls by voice or using the simulator buttons -- is still allowing customizable hotkeys. (Plus, having [i] and [o] is very reminiscent of calls at In and Out... but if people find it easier, they can change their settings) So I'm closing this because it rolls in with #73
