### ISSUE TITLE
Error running Wheatley on fresh install

### ISSUE THREAD

**Issue by BrynMarieR** [lelandpaul/ringingroom#180]
I think I have most things configured correctly, but I'm getting the following error:

```
[2020-10-02 16:09:02,629] INFO in extensions: WHEATLEY:498375621:run-wheatley: error: the following arguments are required: room_id
```

Clearly it has the room ID (498375621), but can't find it also...?

Also, I'm seeing a new process spawn (in the console) every time I assign Wheatley to a bell. These are just subprocesses of the singular Wheatley instance, yes?

@kneasle

**Comment by kneasle** [comment]
The latter issue (the new processes spawning) is I think a side effect of the first - if RR tries to spawn a Wheatley instance but that instance crashes immediately, then next time a bell is assigned to Wheatley, RR will notice that there's no instance running and spawn a new one every time.  Linux also reserves process IDs with 'zombie' processes for a little while in case anything has stored that process ID and tries to contact it (because if another process were allowed to take over then this would be a really nasty error).  So this makes it look like the Wheatley instances are piling up when in fact they are not.

I don't know what's going on with the first error, however... I'll do some tracking down.

**Comment by centreboard** [comment]
Is this still an issue with `0.5.1`?

**Comment by BrynMarieR** [comment]
No
