### ISSUE TITLE
async-mode="threading" blocks WebSockets

### ISSUE THREAD

**Issue by centreboard** [lelandpaul/ringingroom#183]
https://github.com/lelandpaul/ringingroom/blob/d461397280bc27341e60bc577f4637b48fa12b1e/app/extensions.py#L10-L12

With it I get
> WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.

Which is misleading, it actually is blocked by it (eventlet is installed)
https://stackoverflow.com/questions/60991897/websocket-transport-not-available-install-eventlet-or-gevent-and-gevent-websock

And then lots of http polling 
> 127.0.0.1 - - [13/Oct/2020 18:56:05] "POST /socket.io/?transport=polling&EIO=3&sid=3dfbe7f003dc4314940fca77c6b2377e HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2020 18:56:05] "GET /socket.io/?transport=polling&EIO=3&sid=3dfbe7f003dc4314940fca77c6b2377e&t=1602611765.5848458 HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2020 18:56:05] "GET /socket.io/?EIO=3&transport=polling&t=NKZ6k4D&sid=c4ed356de55e41f597f83f01280b2945 HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2020 18:56:07] "POST /socket.io/?EIO=3&transport=polling&t=NKZ6kZK&sid=4920a74f16f94933983f4463bdf68b9e HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2020 18:56:07] "GET /socket.io/?EIO=3&transport=polling&t=NKZ6eI0&sid=4920a74f16f94933983f4463bdf68b9e HTTP/1.1" 200 -

Running both Ringing Room and Wheatley from separate command lines I get a delay and then bells ringing at once in the browser.

Removing this line and restoring using WebSockets seems to work fine with Wheatley running separately and from Ringing Room for me. Do you remember why it was added @kneasle?

**Comment by kneasle** [comment]
I can't exactly remember why it was added, except that I needed to spawn some separate threads for the Wheatley integration and according to the Internet it was needed.  I didn't get any such warnings when I was working on it... 

However, the development server is being extremely laggy since the addition of Wheatley (and by extension, this line of code) so if you think it's causing problems then I think it should be removed.

**Comment by centreboard** [comment]
Ah, you can only see this if you run `python3 ringingroom.py` instead of `flask run`.

It is different between https://ringingroom.com/ 
![image](https://user-images.githubusercontent.com/10487726/96041918-7b1dc880-0e64-11eb-8b30-1ef95d83bb3c.png)
and https://dev.ringingroom.com/
![image](https://user-images.githubusercontent.com/10487726/96041987-97ba0080-0e64-11eb-973a-76fc04a7979d.png)

**Comment by kneasle** [comment]
Aha OK that would explain it - I wondered if it was just me using my system `site-packages` rather than a `venv`, but this makes sense.

**Comment by kneasle** [comment]
I wonder if this is what's causing the behaviour I'm seeing here?

![image](https://user-images.githubusercontent.com/32932209/96128520-61749380-0eed-11eb-8cc8-67494c051d28.png)

This happens if CLI Wheatley connects to a tower, then I close Wheatley with `ctrl-c` and try to reconnect.  It's making testing a bit difficult, because I need to create a new room with 16 bells for every test run `:)`.
