### ISSUE TITLE
eBells and ActionXL controllers Dev version

### ISSUE THREAD

**Issue by mxpidd** [lelandpaul/ringingroom#207]
The dev version is looking very good. I have noticed a couple of things.

Help/Handbell Controllers: End of para  2 the statement that button actions are not implemented is no longer correct, I hadn't updated.

Controllers are not correctly identified on screen when more that two gamepad controllers are identified. The bell and button actions are all fine. The simple fix if to only assign MXP_Type when an eBell or ActionXL is found and throwing warning to remove excess devices if more than two are found. A dropdown select devices would be better but more work. If that option were taken the way is open to add additional setting in the future with little difficulty.

Let me know if you'd like me to attempt this.

**Comment by lelandpaul** [comment]
I've fixed the help file (not on the server yet, but in the repo).

I hadn't really considered that anyone would want to use more than 2 controllers simultaneously, but I've heard from Graham John that it's a pretty common use case and so I think we should support it. I think that this requires really rethinking the UI, though. Bryn & I just talked this over and here's what we came up with (though we're open to feedback on this!):

- The Controllers box consists of a list of connected controllers (similar to the Users box).
- Each controller has the controller type on the left and a set of circled numerals on the right (like the numbers that currently appear in the Users box for assigned bells).
- The circled numerals correspond the bells you are currently assigned to — so if you're assigned to 3-4-5-6, you can select from only those bells — plus an "off" button of some sort.
- Clicking on a circled numeral connects that controller to that bell (or turns it off); if another controller was already connected to that bell, it gets turned off.
- As you get assigned to bells, the controllers are automatically connected to the bells in sorted order — so the first controller in the list gets connected to the highest pitch bell, etc.

We don't use dropdown menus anywhere else in the RR design, so I'd like to avoid introducing them; plus, the circled-number button option outlined here I think allows for swapping bells around more quickly.

Here's how I think we should implement this:
- [ ] The `controllers` component should maintain a mapping from controllers to bell numbers (rather than just a list of controllers).
- [ ] The `send` function should be reworked so that it follows the map from controller to bell, then directly calls the `pull_rope` function of the `bell_circle` component (rather than going through keyboard hotkeys).

I'll need to think about the best way to implement the buttons in Vue, but it shouldn't be too hard.

**Comment by mxpidd** [comment]
I'll think about this tonight and reply tomorrow. I'd been coming from the view of multiple controllers available, but only two being used, rather than multiple pairs being used. I think that making assignment simple in the multi user case might need a little more feedback to help identify controllers.

**Comment by mxpidd** [comment]
Apologies if a bit of a brain dump,
I hope it is comprehensible. 

Help file fix:
Thanks, I should have revisited the help myself. 

Multiple pairs of controllers:
The group with such a requirement is probably small but very active. I agree that supporting this would be good and is worth any delay it causes.

Whilst required for multiple pairs of controllers the whole assignment process is a bit over the top when only one or two controllers are present. I think the simple swap option for this case should be retained as quicker, simpler and a cleaner look for the vast majority of usage. 

I like controller names and circled numbers. The consistency of style is attractive. My dropdown suggestion should have been a list suggestion. 

Should the controllers default be OFF with an initial action required to enable? Given assignment of will be required if the initial value is null then ON is probably ok. If a separate one/two controller option is retained the initial ON/OFF should be consistent. I guess a trade off between having to turn it off each time if you don’t want to use it against having to turn on if you do. A remembered user option?

If no bells are assigned a message, rather than no bells available, would be good to point to the requirement to assign bells. 

I’m not sure about sorting the list of controllers. I don’t see any way to distinguish between four connected eBells other than the arbitrary Gamepad index. It will be confusing if the order changes without being apparent in the list. The Gamepad array order is ok for one session but, I believe, this is established at boot time so may change between sessions. I think allowing a controller to generate a strike, it need not necessarily sound, and highlighting the last rung controller in the list should make assignment straightforward. 

Is a button to show/hide unassigned controllers useful, it need only be visible if there are some. 

Implementation:
I see no problem with your suggestion.

Longer term do you see this as one big step to final product or an ongoing trickle of further developments?

There is a minority of homemade controllers out there that may include some with different outputs or axis orientation systems. There is a choice between adjusting the strike points or the input data which would need consideration if these value were exposed to the user. 

I haven’t included the virtual joystick option but it could be included. My reasons were to limit the active controllers to two and,
hopefully, a close implementation for mobile devices. 

The ActionXL output can lead to false strikes with some handling styles. The strike algorithm can use additional axis information to improve this if necessary, but I’m inclined not to anticipate demand that may not be realised. 

Recognition of other controller types and the data they offer could be handled on a case by case basis if demand exists or by allowing access to settings for each bell to assign axes and strike points and possibly other attributes.

Mike

**Comment by lelandpaul** [comment]
I do take your point that adding the extra interface elements will be unnecessary for the majority of users who use only two controllers at a time; I do like how clean the current interface is for that use case.

The problem, as I see it, is that controllers will nearly always be used in pairs, but that if we see four controllers connected we have no way to determine which are paired. As you mention, the fact that there's no real way to identify individual controllers to the user makes this extra difficult: even if we did display the device ID on screen, there's nothing on the physical device to let users know which ID corresponds to which device. I don't really see a good software solution to this — users will just have to pass controllers around to get them in the right order, I think.

The assigning in sorted order was an attempt to make sure that as many bells as possible "just worked", without the user having to manually assign things, but maybe this just isn't possible and we should make users connect bells manually every time.

Another option that I considered, which I think might be better: Instead of having a list of controllers, have a list of currently assigned bells. Next to each bell, have an "assign" button; when you click that, the next controller to give input gets assigned to that bell. This, I think, minimizes the need to pass bells around between ringers: just click the button and ring the relevant controller and then it's connected.

So here's my new suggestion: If there are exactly two controllers attached, then auto-assign them to the first two bells the user is assigned to and include a "swap" button. If there are more than two controllers, don't auto-assign them, and instead of a "swap" button have a "unassign all" button.

**Comment by mxpidd** [comment]
I agree physically swapping around 4 controllers isn’t a realistic option, to much like playing cats cradle with cables pulling all over the place.

I agree “swap” with two works best.

I really like your suggestion to assign a bell based on next controller action. I think it could work really well.

I’m not sure a deassign all is required. Having a list of bells assigned to the user, with associated option to “assign by controller action” and option to “deassign” would be sufficient.

This has a nice synergy with ringer assignment and it would take no time to deassign unwanted bells.

Is it worth changing the two buttons to accept or reject the assignment once a controller action has been registered. 

An appropriate message would need to be presented if attempting controller assignment when no bells assigned to a user.

**Comment by lelandpaul** [comment]
> Is it worth changing the two buttons to accept or reject the assignment once a controller action has been registered.

I'm not sure what you mean by this. Do you mean, should pressing a button count as an "action" for the purpose of assigning the controller to a bell? If so, I think yes.

I've just created a PR with some initial changes. I did a bunch of refactoring that I think will make this easier. The current draft does somewhat the opposite of what I described above, but I'll change that!

**Comment by mxpidd** [comment]
﻿
Sorry, too many words for buttons/controllers relating to physical devices and software. I haven’t been clear, probably a reflection of a confused thought process. 

I do think including a physical button press as an action to assign a bell to a controller is good - but that isn’t what I intended to convey.

My intention was to suggest that against each bell to which a controller might be assigned there should be two soft controls. These should be, if both applicable, to assign/reassign or deassign controllers from that bell through a controller event. If the option to assign is taken and a controller action event occurs then the soft buttons change to indicate this becoming an accept button and a reject button for this assignment action. This allows for twitchy fingers and to have a positive action to confirm and move on. I’m afraid I’m not clear on correct terminology so am abusing the word “button”. I’m intending it to mean a clickable control within the motion controller panel. Whatever fits in consistently with the site is clearly appropriate. 

I’ll aim to have a look at the PR over the weekend. I’m always hopeful that next week will be quieter.

Mike

**Comment by lelandpaul** [comment]
Ah — that makes more sense. I'll play with this.

I've pushed a bit more to the PR. It still has a couple of known bugs:
1. If you have more than 3 controllers, assign them to bells, then unassign yourself from the bells, you can still ring them.
2. If you have 3 controllers but no bells assigned, (sometimes?) the Swap button still appears
3. the "assign" button appears for each individual bell even when you have only two controllers connected

Plus there's not currently a way to really unassign bells, and sometimes the wrong controller type is shown? (I think that's a Vue issue, but it's very intermittent and I'm having trouble tracking it down.)

**Comment by lelandpaul** [comment]
I put in some more time on this, and have resolved the outstanding problems. I went ahead and merged the PR, but if you want to look at the final changes see #212.

I'm going to deploy this to dev now, and we'll see what comes up in testing.

**Comment by mxpidd** [comment]
This is looking excellent, well done. I had a very quick look a couple of commits back and it all worked fine for me.

I’ll check out the dev version tomorrow and let you know if I pick up on anything. Last I looked, if controllers were removed to leave just two the assignment method didn’t return to swap mode, but I expect a refresh would work.
