### ISSUE TITLE
J & L for 9 and 10 are swapped over

### ISSUE THREAD

**Issue by kneasle** [lelandpaul/ringingroom#223]
Not sure what's going on, but I think it's comparing strings `"9"` to `"10"` (thinking that `"9" > "10"` because `10` starts with `1`).  Weird thing is, I'm not sure what's changed in this update to cause this.

**Comment by BrynMarieR** [comment]
I'm looking into it already. I think it has to do with some of the logic about assigned bells and how we dealt with multiple connected handbell controllers. Should be fixed soon!

**Comment by lelandpaul** [comment]
I was today years old when I learned that Javascript defaults to sorting lists of integers alphabetically: https://stackoverflow.com/questions/1063007/how-to-sort-an-array-of-integers-correctly

No, really. This makes absolutely everything in [the wat talk](https://www.destroyallsoftware.com/talks/wat) seem completely sensible.

This issue is resolved in commit 486033026a8eb757d3d2cdc3fb458a6cce4c8a37, which I'll put live on the server very soon.

**Comment by kneasle** [comment]
_internal screaming_
